default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: thaibhoang # role previously added   
  password: <%= ENV['DATABASE_PASSWORD'] %> # variable previously added

development:
  <<: *default
  database: thaibhoang

test:
  <<: *default
  database: depot_test

production:
  <<: *default
  database: depot_production
  username: depot
  password: <%= ENV["DEPOT_DATABASE_PASSWORD"] %>